### ISSUE TITLE
Account is not allowed to access this API

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [JanJoris/ober#3]
Hi,
I've created the application and assigned it to the store as in docs,
but after trying to create submission app fails with error:
{code : "Unauthorized", message: "Authorization: Account is not allowed to access this API"}

**Comment by JanDeDobbeleer** [comment]
In that case you have to request access to the Submision API. This can be done using the feedback button in the bottom right corner of the Store Dashboard. Select Submission API and request access. 

![image](https://cloud.githubusercontent.com/assets/2492783/18016027/87616660-6bca-11e6-9c17-b4ff44aaaed2.png)

**Comment by Viachaslau-Zinkevich** [comment]
Thanks, will try it!
