### ISSUE TITLE
Add support for *.appxbundle files

### ISSUE THREAD

**Issue by ghost** [JanJoris/ober#6]
I don't know about your system, but when I am compiling an UWP app for the store, MSBuild always creates a `*.appxbundle` file which is a ZIP archive containing all relevant `*.appx` files for the store. It would be nice if ober could support these as well :)

**Comment by ghost** [comment]
Wow. A lot of UWP builds later I found the `appxupload` file that I never used ¯\_(ツ)_/¯

**Comment by JanDeDobbeleer** [comment]
So, can I close this?

**Comment by ghost** [comment]
Yep, I forgot that.
